make:
	killall dunst
	dunstify -u normal "Normal" "Agagagaga"
	dunstify -u low "Low" "Agagagag"
	dunstify -u critical -t 5000 "Critical" "Agagagag"
	dunstify -u low -h int:value:50 -i ~/pics/wallpapers/citySkyes.png "Cool icon" "And cool bar"
